const labels = {
  English: {
    modules: 'Modules',
    learners: 'Learners',
    enroll: 'Enroll Demo Learner',
    progressTitle: 'Your Demo Progress',
    complete: 'Complete',
    continueLearning: 'Continue Learning',
    startLearning: 'Start Learning',
    curriculum: 'Course Curriculum',
    module: 'Module',
    assessment: 'Module Assessment',
    backToCourse: 'Back to course',
    preparingPath: 'Preparing learning path...',
    sectionsCompleted: 'sections completed',
    previous: 'Previous',
    next: 'Next',
    courseNavigation: 'Course Navigation',
    unlockPathHelp: 'Complete sections in order to unlock the path.',
    progress: 'Progress',
    watchTime: 'Watch Time',
    completion: 'Completion',
    completed: 'Completed',
    inProgress: 'In Progress',
    notStarted: 'Not Started',
    watch90: 'Watch 90%',
    courseCompleted: 'Course Completed',
    completionMessage: 'Great work. Your completion percentage and assessment progress are now eligible for certificate review in this POC.',
    assessmentScore: 'Assessment Score',
    recorded: 'Recorded',
    certificate: 'Certificate',
    eligible: 'Eligible',
    reviewCourse: 'Review Course',
    finished: 'Finished learning? Mark as complete to continue.',
    completeTopic: 'Complete Topic',
    watchToUnlock: 'Watch 90% to unlock next section',
    videoUnlockHelp: 'Video lessons unlock after 90% watch progress.',
    interactiveTitle: 'Interactive Exercise Preview',
    interactiveText: 'This POC simulates the exercise flow for client walkthroughs.',
    launchExercise: 'Launch Exercise',
    backToLesson: 'Back to lesson',
    noAssessment: 'No assessment found',
    submitAssessment: 'Submit Assessment',
    returnToCourse: 'Return to Course',
    score: 'Score',
    passed: 'Passed',
    tryAgain: 'Try again',
    answerPrompt: 'Answer the questions below to simulate module completion.',
    enrolled: 'Enrolled',
    levels: {
      beginner: 'beginner',
      intermediate: 'intermediate',
      advanced: 'advanced',
    },
  },
  Hindi: {
    modules: 'मॉड्यूल',
    learners: 'सीखने वाले',
    enroll: 'डेमो शिक्षार्थी नामांकित करें',
    progressTitle: 'आपकी डेमो प्रगति',
    complete: 'पूर्ण',
    continueLearning: 'सीखना जारी रखें',
    startLearning: 'सीखना शुरू करें',
    curriculum: 'पाठ्यक्रम संरचना',
    module: 'मॉड्यूल',
    assessment: 'मॉड्यूल आकलन',
    backToCourse: 'पाठ्यक्रम पर वापस जाएं',
    preparingPath: 'लर्निंग पाथ तैयार हो रहा है...',
    sectionsCompleted: 'सेक्शन पूर्ण',
    previous: 'पिछला',
    next: 'अगला',
    courseNavigation: 'कोर्स नेविगेशन',
    unlockPathHelp: 'पाथ अनलॉक करने के लिए सेक्शन क्रम से पूर्ण करें।',
    progress: 'प्रगति',
    watchTime: 'देखने का समय',
    completion: 'पूर्णता',
    completed: 'पूर्ण',
    inProgress: 'प्रगति में',
    notStarted: 'शुरू नहीं',
    watch90: '90% देखें',
    courseCompleted: 'कोर्स पूर्ण हुआ',
    completionMessage: 'बहुत अच्छा। इस POC में आपकी पूर्णता प्रतिशत और आकलन प्रगति अब प्रमाणपत्र समीक्षा के लिए योग्य है।',
    assessmentScore: 'आकलन स्कोर',
    recorded: 'रिकॉर्ड किया गया',
    certificate: 'प्रमाणपत्र',
    eligible: 'योग्य',
    reviewCourse: 'कोर्स रिव्यू करें',
    finished: 'सीखना पूरा हुआ? आगे बढ़ने के लिए पूर्ण चिह्नित करें।',
    completeTopic: 'विषय पूर्ण करें',
    watchToUnlock: '90% देखें और अगला सेक्शन अनलॉक करें',
    videoUnlockHelp: 'वीडियो पाठ 90% देखने के बाद अगला सेक्शन अनलॉक करते हैं।',
    interactiveTitle: 'इंटरैक्टिव अभ्यास पूर्वावलोकन',
    interactiveText: 'यह POC क्लाइंट प्रस्तुति के लिए अभ्यास प्रवाह दिखाता है।',
    launchExercise: 'अभ्यास शुरू करें',
    backToLesson: 'पाठ पर वापस जाएं',
    noAssessment: 'कोई आकलन नहीं मिला',
    submitAssessment: 'आकलन जमा करें',
    returnToCourse: 'पाठ्यक्रम पर लौटें',
    score: 'स्कोर',
    passed: 'उत्तीर्ण',
    tryAgain: 'फिर प्रयास करें',
    answerPrompt: 'मॉड्यूल पूरा करने के लिए नीचे दिए गए प्रश्नों के उत्तर दें।',
    enrolled: 'नामांकित',
    levels: {
      beginner: 'शुरुआती',
      intermediate: 'मध्यम',
      advanced: 'उन्नत',
    },
  },
  Gujarati: {
    modules: 'મોડ્યુલ',
    learners: 'શીખનાર',
    enroll: 'ડેમો શીખનાર નોંધાવો',
    progressTitle: 'તમારી ડેમો પ્રગતિ',
    complete: 'પૂર્ણ',
    continueLearning: 'શીખવાનું ચાલુ રાખો',
    startLearning: 'શીખવાનું શરૂ કરો',
    curriculum: 'કોર્સ અભ્યાસક્રમ',
    module: 'મોડ્યુલ',
    assessment: 'મોડ્યુલ મૂલ્યાંકન',
    backToCourse: 'કોર્સ પર પાછા જાઓ',
    preparingPath: 'લર્નિંગ પાથ તૈયાર થઈ રહ્યો છે...',
    sectionsCompleted: 'સેક્શન પૂર્ણ',
    previous: 'પાછલું',
    next: 'આગળ',
    courseNavigation: 'કોર્સ નેવિગેશન',
    unlockPathHelp: 'પાથ અનલોક કરવા માટે સેક્શન ક્રમથી પૂર્ણ કરો.',
    progress: 'પ્રગતિ',
    watchTime: 'જોવાનો સમય',
    completion: 'પૂર્ણતા',
    completed: 'પૂર્ણ',
    inProgress: 'ચાલુ છે',
    notStarted: 'શરૂ નથી',
    watch90: '90% જુઓ',
    courseCompleted: 'કોર્સ પૂર્ણ થયો',
    completionMessage: 'સરસ કામ. આ POC માં તમારી પૂર્ણતા ટકાવારી અને મૂલ્યાંકન પ્રગતિ હવે પ્રમાણપત્ર સમીક્ષા માટે યોગ્ય છે.',
    assessmentScore: 'મૂલ્યાંકન સ્કોર',
    recorded: 'રેકોર્ડ થયું',
    certificate: 'પ્રમાણપત્ર',
    eligible: 'યોગ્ય',
    reviewCourse: 'કોર્સ રિવ્યુ કરો',
    finished: 'શીખવું પૂર્ણ થયું? આગળ વધવા માટે પૂર્ણ તરીકે ચિહ્નિત કરો.',
    completeTopic: 'વિષય પૂર્ણ કરો',
    watchToUnlock: '90% જુઓ અને આગળનો સેક્શન અનલોક કરો',
    videoUnlockHelp: 'વિડિઓ પાઠ 90% જોયા પછી આગળનો સેક્શન અનલોક કરે છે.',
    interactiveTitle: 'ઇન્ટરેક્ટિવ અભ્યાસ પૂર્વાવલોકન',
    interactiveText: 'આ POC ક્લાયન્ટ રજૂઆત માટે અભ્યાસ પ્રવાહ બતાવે છે.',
    launchExercise: 'અભ્યાસ શરૂ કરો',
    backToLesson: 'પાઠ પર પાછા જાઓ',
    noAssessment: 'કોઈ મૂલ્યાંકન મળ્યું નથી',
    submitAssessment: 'મૂલ્યાંકન સબમિટ કરો',
    returnToCourse: 'કોર્સ પર પાછા જાઓ',
    score: 'સ્કોર',
    passed: 'પાસ',
    tryAgain: 'ફરી પ્રયાસ કરો',
    answerPrompt: 'મોડ્યુલ પૂર્ણ કરવા માટે નીચેના પ્રશ્નોના જવાબ આપો.',
    enrolled: 'નોંધાયેલા',
    levels: {
      beginner: 'શરૂઆત',
      intermediate: 'મધ્યમ',
      advanced: 'ઉન્નત',
    },
  },
};

export function courseLabels(language) {
  return labels[language] || labels.English;
}

export function formatLevel(level, language) {
  const t = courseLabels(language);
  return t.levels?.[level] || level;
}
